name: guilherme1guy-pi2-autoosball # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Server Control software for a PI2 project called Autoosball # 79 char long summary
description: |
  This snap is the control software for a project for a class on University of Brasilia.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  autoosball:
    command: /bin/bash start.sh

parts:
  autoosball:
    source: https://github.com/pi2-2020-1-pebolim/foosball_decision_server.git
    plugin: python
    python-version: 'python3'